// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.27;

import {IZkVerifier} from "../interfaces/IZkVerifier.sol";

/// @title VkRegistry
/// @notice Single source of truth for the 11 circuit verification-key hashes.
/// @dev Spec: design-v2/subsystems/02_zk_circuits.md §2 (the 12 circuits;
///            v1 ships 11, with bucket_refresh deferred to v1.5).
///      Each constant is the Keccak-format vkHash (1888 bytes) generated by
///      `bb.js` with `keccakZK: true` for zkVerify compatibility. VKs derived
///      from circuits in `code/circuits/<circuit>/` using
///      `code/dapp/scripts/derive-vks.mjs`.
///
///      2026-08-19: Updated from Poseidon2 (3680 bytes) to Keccak format
///      (1888 bytes) as required by zkVerify's UltraHonk V3_0 pallet.
///
///      `pack()` returns a `bytes32[NUM_CIRCUITS]` ordered to match the
///      `IZkVerifier.CircuitId` enum — feed it to `new ZkVerifier(...)`.
library VkRegistry {
    // Updated 2026-08-19: Keccak format VK hashes (1888 bytes)
    // These match the Kurier-registered VKs in kurier-vk-hashes.ts

    bytes32 internal constant ENTRY_DEPOSIT =
        0x0063b1d06d07c6c2f95c85450bf47e324fd92901fa0009ecf1193a80ea8a4270;
    bytes32 internal constant ENTRY_WITHDRAW =
        0x7f23d01f0f374830c798db6f83f5bd016468d036437628ddfc762f8b513a823c;
    bytes32 internal constant SUPPLY_ASSET =
        0x6d827ab8e9cda14748279168d08e083b72fa7469e8fe83226e5ccf77118be373;
    bytes32 internal constant WITHDRAW_SUPPLY =
        0xd6f1bb92d97aa596b227aa556f0b4010761c6ee55780b27c1397c5927497efc2;
    bytes32 internal constant DEPOSIT_COLLATERAL =
        0xb14b868cd59033bc935723bd1b427c1128df838a180a6be878f9a5da08346704;
    bytes32 internal constant WITHDRAW_COLLATERAL =
        0x28499c36b7cf01004d99578626afbbc9843b88a0e829f8c540830f5ef96c4c8a;
    bytes32 internal constant BORROW =
        0xd8683cd6f52f93cb0ca080b964e29c9b83048fdbdbe4488c2546ce540b5f7568;
    bytes32 internal constant REPAY =
        0xca9cd26328f61b020accacbbba348bf8d783dc78e9d6eba54ed007d6535e50b4;
    bytes32 internal constant LIQUIDATE =
        0xac31cdb92f463d7958513b4fd52b688c4444ef631a6ef75614d9bad6619f27db;
    bytes32 internal constant CONSOLIDATE_BALANCE =
        0xf45292467c13d34aeb8654e23bb2e8976954aedfc8d1c82395a5feb4b1480a48;
    bytes32 internal constant COMPUTE_TRIGGERS =
        0x26f19d4f331dd3905d3eda2b9254ca4da3252cb8fad7d170fe5cd5a4bc1c2bb7;

    /// @return out an 11-slot array indexed by `IZkVerifier.CircuitId`.
    function pack() internal pure returns (bytes32[] memory out) {
        out = new bytes32[](11);
        out[uint8(IZkVerifier.CircuitId.ENTRY_DEPOSIT)] = ENTRY_DEPOSIT;
        out[uint8(IZkVerifier.CircuitId.ENTRY_WITHDRAW)] = ENTRY_WITHDRAW;
        out[uint8(IZkVerifier.CircuitId.SUPPLY_ASSET)] = SUPPLY_ASSET;
        out[uint8(IZkVerifier.CircuitId.WITHDRAW_SUPPLY)] = WITHDRAW_SUPPLY;
        out[uint8(IZkVerifier.CircuitId.DEPOSIT_COLLATERAL)] = DEPOSIT_COLLATERAL;
        out[uint8(IZkVerifier.CircuitId.WITHDRAW_COLLATERAL)] = WITHDRAW_COLLATERAL;
        out[uint8(IZkVerifier.CircuitId.BORROW)] = BORROW;
        out[uint8(IZkVerifier.CircuitId.REPAY)] = REPAY;
        out[uint8(IZkVerifier.CircuitId.LIQUIDATE)] = LIQUIDATE;
        out[uint8(IZkVerifier.CircuitId.CONSOLIDATE_BALANCE)] = CONSOLIDATE_BALANCE;
        out[uint8(IZkVerifier.CircuitId.COMPUTE_TRIGGERS)] = COMPUTE_TRIGGERS;
    }
}
